# https://www.home-assistant.io/integrations/default_config/
#default_config:

homeassistant:
  name: Dev
  unit_system: metric
  time_zone: Europe/Oslo

# ðŸ”¹ Kjerne som trengs for UI og utvikling (uten default_config):
frontend:
http:
api:
websocket_api:
system_health:
config:
isal:


# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    custom_components.somweb: debug
